WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
WHENEVER OSERROR EXIT 9 ROLLBACK

SET SERVEROUTPUT ON
SET FEEDBACK ON
SET VERIFY OFF
SET DEFINE ON

PROMPT Creating application schema MYAPP and development user MIKE
PROMPT Usage: @admin/00_create_myapp_and_mike.sql "<schema_password>"

DECLARE
  v_count NUMBER;
  v_password VARCHAR2(256) := '&&1';
BEGIN
  IF v_password IS NULL THEN
    RAISE_APPLICATION_ERROR(-20000, 'A schema password must be provided as the first script argument.');
  END IF;

  SELECT COUNT(*)
  INTO   v_count
  FROM   dba_users
  WHERE  username = 'MYAPP';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER MYAPP IDENTIFIED BY "' || REPLACE(v_password, '"', '""') || '" DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON DATA';
    DBMS_OUTPUT.PUT_LINE('Created user MYAPP');
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER MYAPP IDENTIFIED BY "' || REPLACE(v_password, '"', '""') || '" ACCOUNT UNLOCK';
    EXECUTE IMMEDIATE 'ALTER USER MYAPP DEFAULT TABLESPACE DATA';
    EXECUTE IMMEDIATE 'ALTER USER MYAPP TEMPORARY TABLESPACE TEMP';
    EXECUTE IMMEDIATE 'ALTER USER MYAPP QUOTA UNLIMITED ON DATA';
    DBMS_OUTPUT.PUT_LINE('Updated existing user MYAPP');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_password VARCHAR2(256) := '&&1';
BEGIN
  IF v_password IS NULL THEN
    RAISE_APPLICATION_ERROR(-20000, 'A schema password must be provided as the first script argument.');
  END IF;

  SELECT COUNT(*)
  INTO   v_count
  FROM   dba_users
  WHERE  username = 'MIKE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER MIKE IDENTIFIED BY "' || REPLACE(v_password, '"', '""') || '" DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON DATA';
    DBMS_OUTPUT.PUT_LINE('Created user MIKE');
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER MIKE IDENTIFIED BY "' || REPLACE(v_password, '"', '""') || '" ACCOUNT UNLOCK';
    EXECUTE IMMEDIATE 'ALTER USER MIKE DEFAULT TABLESPACE DATA';
    EXECUTE IMMEDIATE 'ALTER USER MIKE TEMPORARY TABLESPACE TEMP';
    EXECUTE IMMEDIATE 'ALTER USER MIKE QUOTA UNLIMITED ON DATA';
    DBMS_OUTPUT.PUT_LINE('Updated existing user MIKE');
  END IF;
END;
/

GRANT CREATE SESSION,
      ALTER SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE SEQUENCE,
      CREATE PROCEDURE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE SYNONYM,
      CREATE JOB
TO MYAPP;

GRANT CREATE SESSION,
      ALTER SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE SEQUENCE,
      CREATE PROCEDURE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE SYNONYM,
      CREATE JOB
TO MIKE;

ALTER USER MYAPP GRANT CONNECT THROUGH MIKE;

PROMPT Done. MIKE can work in MYAPP using proxy syntax: MIKE[MYAPP]/password@service

EXIT 0
