#!/bin/bash

# Initialize the SQLcl Project once and synchronize the scaffold with GitHub.

set -euo pipefail

RED='\033[31m'
GREEN='\033[32m'
BLUE='\033[34m'
YELLOW='\033[33m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/setup_env.sh"

GITHUB_ACTIONS_TEMPLATE_DIR="$DEMO_HOME/templates/github-actions"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo -e "${RED}ERROR: $1 not found in PATH${NC}"
    exit 1
  }
}

configure_git_identity() {
  git config user.name "$GIT_AUTHOR_NAME"
  git config user.email "$GIT_AUTHOR_EMAIL"
}

prompt_default() {
  local prompt_text="$1"
  local default_value="$2"
  local answer

  read -r -p "$prompt_text [$default_value]: " answer
  printf '%s' "${answer:-$default_value}"
}

validate_project_name() {
  local value="$1"

  if [[ ! "$value" =~ ^[A-Za-z][A-Za-z0-9_]*$ ]]; then
    echo -e "${RED}ERROR: Project name must start with a letter and contain only letters, numbers, and underscores.${NC}"
    exit 1
  fi
}

validate_schema_name() {
  local value="$1"
  local schema_pattern='^[A-Z][A-Z0-9_$#]*$'

  if [[ ! "$value" =~ $schema_pattern ]]; then
    echo -e "${RED}ERROR: Default schema must be a valid unquoted Oracle schema name.${NC}"
    exit 1
  fi
}

write_demo_selection_env() {
  cat > "$DEMO_SELECTION_ENV" <<EOF
#!/bin/bash

# Generated by run/create_project.sh.
# Stores the selected SQLcl Project name and default schema for follow-up scripts.

export PROJECT_NAME="$PROJECT_NAME"
export SCHEMA_NAME="$SCHEMA_NAME"
EOF
}

append_filter_once() {
  local filter_line="$1"
  local filter_comment="$2"

  if grep -Fq "$filter_line" "$FILTERS_FILE"; then
    echo -e "${GREEN}Filter already present: $filter_line${NC}"
  else
    {
      echo ""
      echo "$filter_comment"
      echo "$filter_line"
    } >> "$FILTERS_FILE"
    echo -e "${GREEN}Added filter: $filter_line${NC}"
  fi
}

install_github_actions_templates() {
  if [[ ! -d "$GITHUB_ACTIONS_TEMPLATE_DIR/.github" ]]; then
    echo -e "${RED}ERROR: GitHub Actions templates not found: $GITHUB_ACTIONS_TEMPLATE_DIR${NC}"
    exit 1
  fi

  echo -e "${BLUE}Installing GitHub Actions templates from $GITHUB_ACTIONS_TEMPLATE_DIR...${NC}"
  mkdir -p "$PROJECT_DIR/.github"
  cp -R "$GITHUB_ACTIONS_TEMPLATE_DIR/.github/." "$PROJECT_DIR/.github/"

  if [[ -f "$PROJECT_DIR/.github/scripts/check-sqlcl-verify-output.sh" ]]; then
    chmod +x "$PROJECT_DIR/.github/scripts/check-sqlcl-verify-output.sh"
  fi
}

echo ""
echo -e "${BLUE}This script initializes the SQLcl Project once.${NC}"

PROJECT_NAME="$(prompt_default "Project name" "$PROJECT_NAME")"
SCHEMA_NAME="$(prompt_default "Default schema" "$SCHEMA_NAME")"
SCHEMA_NAME="$(printf '%s' "$SCHEMA_NAME" | tr '[:lower:]' '[:upper:]')"

validate_project_name "$PROJECT_NAME"
validate_schema_name "$SCHEMA_NAME"
export PROJECT_NAME
export SCHEMA_NAME

PROJECT_DIR="$PROJECTS_HOME/$PROJECT_NAME"
FILTERS_FILE="$PROJECT_DIR/.dbtools/filters/project.filters"
CONFIG_FILE="$PROJECT_DIR/.dbtools/project.config.json"

echo -e "${BLUE}Project folder:   $PROJECT_DIR${NC}"
echo -e "${BLUE}Schema:           $SCHEMA_NAME${NC}"
echo -e "${BLUE}DB connection:    $DB_CONNECT_DEV${NC}"
echo -e "${BLUE}GitHub remote:    $GITHUB_URL${NC}"
echo -e "${BLUE}CI templates:     $GITHUB_ACTIONS_TEMPLATE_DIR${NC}"
echo -e "${BLUE}Git author:       $GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>${NC}"
echo ""

require_cmd sql
require_cmd git
require_cmd gh
require_cmd jq

write_demo_selection_env
echo -e "${GREEN}Saved demo selection: $DEMO_SELECTION_ENV${NC}"

if ! gh auth status >/dev/null 2>&1; then
  echo -e "${RED}ERROR: GitHub CLI is not authenticated.${NC}"
  echo -e "${YELLOW}Run: gh auth login${NC}"
  exit 1
fi

PROJECT_SCAFFOLD_EXISTS=false
if [[ -d "$PROJECT_DIR" ]]; then
  if [[ -f "$CONFIG_FILE" ]]; then
    PROJECT_SCAFFOLD_EXISTS=true
    if [[ -d "$PROJECT_DIR/.git" ]]; then
      echo -e "${YELLOW}Existing SQLcl Project scaffold found with Git metadata.${NC}"
      echo -e "${YELLOW}The script will resume project configuration and Git synchronization.${NC}"
    else
      echo -e "${YELLOW}Existing SQLcl Project scaffold found without Git metadata.${NC}"
      echo -e "${YELLOW}The script will resume from project configuration.${NC}"
    fi
  else
    echo -e "${RED}ERROR: $PROJECT_DIR already exists.${NC}"
    echo -e "${YELLOW}Use cleanup_demo.sh or remove it manually before reinitializing.${NC}"
    exit 1
  fi
fi

if [[ "$PROJECT_SCAFFOLD_EXISTS" == "false" ]]; then
  echo -e "${BLUE}Moving to projects directory: $PROJECTS_HOME${NC}"
  cd "$PROJECTS_HOME"

  echo ""
  echo -e "${BLUE}Initializing SQLcl Project...${NC}"
  echo -e "${GREEN}sql -name \"$DB_CONNECT_DEV\"${NC}"
  echo -e "${YELLOW}project init -name $PROJECT_NAME -schemas $SCHEMA_NAME -makeroot${NC}"
  echo ""
  read -p "Press Enter to execute project init..." -r

  sql -name "$DB_CONNECT_DEV" <<EOF
project init -name $PROJECT_NAME -schemas $SCHEMA_NAME -makeroot
exit
EOF
fi

cd "$PROJECT_DIR"

echo ""
echo -e "${BLUE}Setting SQLcl Project default branch to $GIT_DEFAULT_BRANCH...${NC}"
sql /nolog <<EOF
project config set -name git.defaultBranch -value $GIT_DEFAULT_BRANCH
exit
EOF

echo ""
echo -e "${BLUE}Clearing local SQLcl connection binding from project configuration...${NC}"
tmp_config="$(mktemp)"
jq '.sqlcl.connectionName = ""' "$CONFIG_FILE" > "$tmp_config"
mv "$tmp_config" "$CONFIG_FILE"

if ! grep -q "\"defaultBranch\" *: *\"$GIT_DEFAULT_BRANCH\"" "$CONFIG_FILE"; then
  echo -e "${RED}ERROR: git.defaultBranch was not set to $GIT_DEFAULT_BRANCH in $CONFIG_FILE.${NC}"
  exit 1
fi

if ! jq -e '.sqlcl.connectionName == ""' "$CONFIG_FILE" >/dev/null; then
  echo -e "${RED}ERROR: sqlcl.connectionName is not empty in $CONFIG_FILE.${NC}"
  exit 1
fi

if [[ -f "$CONFIG_FILE" ]] && grep -q '"emitSchema" *: *true' "$CONFIG_FILE"; then
  echo -e "${BLUE}Setting emitSchema=false in project.config.json...${NC}"
  sed -i 's/"emitSchema" *: *true/"emitSchema" : false/' "$CONFIG_FILE"
fi

echo ""
echo -e "${BLUE}Adding project export filters...${NC}"
append_filter_once "object_name not like 'DBTOOLS$%'," "-- Exclude DBTools/MCP support objects from project exports"
append_filter_once "(object_name is null or object_name != 'PROJECT_CONTROL')," "-- Exclude production deployment control table from project exports"
append_filter_once "export_type != 'ORDS_SCHEMA'," "-- Exclude ORDS modules owned by the schema; dashboard ORDS is managed outside SQLcl Projects"

echo ""
echo -e "${BLUE}Creating project README.md...${NC}"
cat > "$PROJECT_DIR/README.md" <<EOF
# $PROJECT_NAME

Oracle SQLcl Projects demo for database CI/CD using schema $SCHEMA_NAME.

## Local demo flow

1. Initialize the project once with \`run/create_project.sh\`.
2. Apply database changes manually in SQLcl using the scripts under the demo folder.
3. Capture each development cycle with \`run/dev_cycle.sh <cycle_name>\`.

## GitHub Actions flow

- Development branch pushes run SQLcl Project verify.
- After a branch is merged to \`main\`, run the \`SQLcl Project Release\` workflow manually.
- The release workflow asks for a version, runs \`project release\`, runs \`project gen-artifact\`, commits the closed release state to \`main\`, and publishes the generated ZIP in GitHub Releases.
- The \`SQLcl Project Deploy\` workflow can list available GitHub Release artifacts, generate a production deploy preview with \`lb update-sql\`, or deploy a selected ZIP with \`project deploy\`.
- The \`SQLcl Project Controlled Deploy\` workflow creates/uses \`PROJECT_CONTROL\`, generates a preview, waits on the GitHub Environment \`production\`, deploys after approval, and records the deployed version.

## SQLcl connections

The project configuration keeps sqlcl.connectionName empty.
Development scripts pass this local connection explicitly:

\`\`\`text
$DB_CONNECT_DEV
\`\`\`

Future GitHub Actions jobs can use environment-specific connections or direct
credentials for validation, release, artifact generation, and deployment.
The validation workflow connects directly to Autonomous Database with
\`connect -cloudconfig\`; it does not create or reuse a saved SQLcl connection.

## Notes

- Local development cycles run \`project export\` and \`project stage\`.
- Release creation and artifact generation are handled by the manual GitHub Actions release workflow.
- Deployment is handled by a separate manual GitHub Actions workflow with \`list\`, \`preview\`, and \`deploy\` operations.
- GitHub Actions workflows are installed by the local demo runner during project creation.
- Export filters exclude DBTools/MCP support objects such as \`DBTOOLS\$MCP_LOG\`, production deployment metadata such as \`PROJECT_CONTROL\`, and ORDS modules such as the optional demo dashboard API.
EOF

echo ""
install_github_actions_templates

echo ""
echo -e "${BLUE}Review filters and project configuration before Git commit:${NC}"
echo -e "${YELLOW}$FILTERS_FILE${NC}"
echo -e "${YELLOW}$CONFIG_FILE${NC}"
read -p "Press Enter when ready to initialize Git and push main..." -r

if [[ ! -d ".git" ]]; then
  echo -e "${BLUE}Initializing Git repository on branch $GIT_DEFAULT_BRANCH...${NC}"
  git init --initial-branch="$GIT_DEFAULT_BRANCH"
fi

configure_git_identity

if ! git remote | grep -q '^origin$'; then
  echo -e "${BLUE}Adding remote origin: $GITHUB_URL${NC}"
  git remote add origin "$GITHUB_URL"
fi

git add .
if git commit -m "chore: initialize SQLcl project for $SCHEMA_NAME"; then
  echo -e "${GREEN}Project scaffold committed.${NC}"
else
  echo -e "${YELLOW}Nothing to commit.${NC}"
fi

echo ""
echo -e "${YELLOW}GitHub Actions validation runs automatically on branch pushes except $GIT_DEFAULT_BRANCH.${NC}"
echo -e "${YELLOW}The initial scaffold push to $GIT_DEFAULT_BRANCH does not trigger project verify.${NC}"
echo -e "${YELLOW}Configure the target database secrets now if you want development branches to validate automatically.${NC}"
read -r -p "Configure GitHub Actions secrets now? [y/N]: " configure_actions_now

case "$configure_actions_now" in
  y|Y|yes|YES)
    "$SCRIPT_DIR/configure_github_actions.sh"
    ;;
  *)
    echo -e "${YELLOW}Skipping GitHub Actions secret configuration. Run configure_github_actions.sh before pushing development branches if you want validation to run.${NC}"
    ;;
esac

echo ""
echo -e "${YELLOW}About to push $GIT_DEFAULT_BRANCH to $GITHUB_URL using --force-with-lease.${NC}"
echo -e "${YELLOW}This is intended for resetting the demo repository scaffold.${NC}"
read -p "Press Enter to push, or Ctrl+C to abort..." -r

echo -e "${BLUE}Refreshing remote branch state before force-with-lease...${NC}"
if git ls-remote --exit-code --heads origin "$GIT_DEFAULT_BRANCH" >/dev/null 2>&1; then
  git fetch origin "$GIT_DEFAULT_BRANCH"
else
  echo -e "${YELLOW}Remote branch $GIT_DEFAULT_BRANCH does not exist yet.${NC}"
fi

git push -u origin "$GIT_DEFAULT_BRANCH" --force-with-lease

echo ""
echo -e "${GREEN}Project initialized and synchronized with GitHub.${NC}"
echo -e "${BLUE}Project directory: $PROJECT_DIR${NC}"
