#!/bin/bash

# Common configuration for the MyApp SQLcl Projects CI/CD demo.

export DEMO_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export DEVELOPER_NAME="${DEVELOPER_NAME:-MIKE}"
export PROJECTS_HOME="$DEMO_HOME/$DEVELOPER_NAME/projects"
export DEMO_SELECTION_ENV="$DEMO_HOME/run/.demo_selection.env"

export PROJECT_NAME_DEFAULT="${PROJECT_NAME_DEFAULT:-MyAppCICD}"
export SCHEMA_NAME_DEFAULT="${SCHEMA_NAME_DEFAULT:-MYAPP}"
export DB_CONNECT_DEV="${DB_CONNECT_DEV:-MIKE[MYAPP]}"
export DB_CONNECT_PROD="${DB_CONNECT_PROD:-MYAPP_PRO}"
export TARGET_WALLET_ZIP_DEFAULT="${TARGET_WALLET_ZIP_DEFAULT:-}"

export DEMO_DASHBOARD_DEV_API_BASE_URL="${DEMO_DASHBOARD_DEV_API_BASE_URL:-}"
export DEMO_DASHBOARD_PROD_API_BASE_URL="${DEMO_DASHBOARD_PROD_API_BASE_URL:-}"
export DEMO_DASHBOARD_REFRESH_SECONDS="${DEMO_DASHBOARD_REFRESH_SECONDS:-10}"
export DEMO_DASHBOARD_PORT="${DEMO_DASHBOARD_PORT:-8088}"

if [[ -f "$DEMO_SELECTION_ENV" ]]; then
  # Generated by create_project.sh. Keeps follow-up scripts aligned with the
  # selected project and default schema.
  source "$DEMO_SELECTION_ENV"
fi

export PROJECT_NAME="${PROJECT_NAME:-$PROJECT_NAME_DEFAULT}"
export SCHEMA_NAME="${SCHEMA_NAME:-$SCHEMA_NAME_DEFAULT}"

export GITHUB_USER="${GITHUB_USER:-vmendo}"
export GITHUB_REPO="${GITHUB_REPO:-MyAppCICD}"
export GITHUB_URL="https://github.com/$GITHUB_USER/$GITHUB_REPO.git"

export GIT_DEFAULT_BRANCH="main"
export GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-vmendo}"
export GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-20044697+vmendo@users.noreply.github.com}"

# The SQLcl wrapper on this host may point to an old Java 21 path.
# Keep this override local to the demo scripts.
export SQLCL_JAVA_HOME="${SQLCL_JAVA_HOME:-}"
if [[ -d "$SQLCL_JAVA_HOME" ]]; then
  export JAVA_HOME="$SQLCL_JAVA_HOME"
  export PATH="$JAVA_HOME/bin:$PATH"
fi

mkdir -p "$PROJECTS_HOME"
